/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NuevoCarritoRouteImport } from './routes/nuevo.carrito'
import { Route as NuevoCategoriaRouteImport } from './routes/nuevo.categoria'
import { Route as NuevoConfirmacionRouteImport } from './routes/nuevo.confirmacion'
import { Route as NuevoConfirmarRouteImport } from './routes/nuevo.confirmar'
import { Route as NuevoMensajeRouteImport } from './routes/nuevo.mensaje'
import { Route as NuevoPagoRouteImport } from './routes/nuevo.pago'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NuevoCarritoRoute = NuevoCarritoRouteImport.update({
  id: '/nuevo/carrito',
  path: '/nuevo/carrito',
  getParentRoute: () => rootRouteImport,
} as any)
const NuevoCategoriaRoute = NuevoCategoriaRouteImport.update({
  id: '/nuevo/categoria',
  path: '/nuevo/categoria',
  getParentRoute: () => rootRouteImport,
} as any)
const NuevoConfirmacionRoute = NuevoConfirmacionRouteImport.update({
  id: '/nuevo/confirmacion',
  path: '/nuevo/confirmacion',
  getParentRoute: () => rootRouteImport,
} as any)
const NuevoConfirmarRoute = NuevoConfirmarRouteImport.update({
  id: '/nuevo/confirmar',
  path: '/nuevo/confirmar',
  getParentRoute: () => rootRouteImport,
} as any)
const NuevoMensajeRoute = NuevoMensajeRouteImport.update({
  id: '/nuevo/mensaje',
  path: '/nuevo/mensaje',
  getParentRoute: () => rootRouteImport,
} as any)
const NuevoPagoRoute = NuevoPagoRouteImport.update({
  id: '/nuevo/pago',
  path: '/nuevo/pago',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/nuevo/carrito': typeof NuevoCarritoRoute
  '/nuevo/categoria': typeof NuevoCategoriaRoute
  '/nuevo/confirmacion': typeof NuevoConfirmacionRoute
  '/nuevo/confirmar': typeof NuevoConfirmarRoute
  '/nuevo/mensaje': typeof NuevoMensajeRoute
  '/nuevo/pago': typeof NuevoPagoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/nuevo/carrito': typeof NuevoCarritoRoute
  '/nuevo/categoria': typeof NuevoCategoriaRoute
  '/nuevo/confirmacion': typeof NuevoConfirmacionRoute
  '/nuevo/confirmar': typeof NuevoConfirmarRoute
  '/nuevo/mensaje': typeof NuevoMensajeRoute
  '/nuevo/pago': typeof NuevoPagoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/nuevo/carrito': typeof NuevoCarritoRoute
  '/nuevo/categoria': typeof NuevoCategoriaRoute
  '/nuevo/confirmacion': typeof NuevoConfirmacionRoute
  '/nuevo/confirmar': typeof NuevoConfirmarRoute
  '/nuevo/mensaje': typeof NuevoMensajeRoute
  '/nuevo/pago': typeof NuevoPagoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/nuevo/carrito'
    | '/nuevo/categoria'
    | '/nuevo/confirmacion'
    | '/nuevo/confirmar'
    | '/nuevo/mensaje'
    | '/nuevo/pago'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/nuevo/carrito'
    | '/nuevo/categoria'
    | '/nuevo/confirmacion'
    | '/nuevo/confirmar'
    | '/nuevo/mensaje'
    | '/nuevo/pago'
  id:
    | '__root__'
    | '/'
    | '/nuevo/carrito'
    | '/nuevo/categoria'
    | '/nuevo/confirmacion'
    | '/nuevo/confirmar'
    | '/nuevo/mensaje'
    | '/nuevo/pago'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NuevoCarritoRoute: typeof NuevoCarritoRoute
  NuevoCategoriaRoute: typeof NuevoCategoriaRoute
  NuevoConfirmacionRoute: typeof NuevoConfirmacionRoute
  NuevoConfirmarRoute: typeof NuevoConfirmarRoute
  NuevoMensajeRoute: typeof NuevoMensajeRoute
  NuevoPagoRoute: typeof NuevoPagoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nuevo/carrito': {
      id: '/nuevo/carrito'
      path: '/nuevo/carrito'
      fullPath: '/nuevo/carrito'
      preLoaderRoute: typeof NuevoCarritoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nuevo/categoria': {
      id: '/nuevo/categoria'
      path: '/nuevo/categoria'
      fullPath: '/nuevo/categoria'
      preLoaderRoute: typeof NuevoCategoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nuevo/confirmacion': {
      id: '/nuevo/confirmacion'
      path: '/nuevo/confirmacion'
      fullPath: '/nuevo/confirmacion'
      preLoaderRoute: typeof NuevoConfirmacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nuevo/confirmar': {
      id: '/nuevo/confirmar'
      path: '/nuevo/confirmar'
      fullPath: '/nuevo/confirmar'
      preLoaderRoute: typeof NuevoConfirmarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nuevo/mensaje': {
      id: '/nuevo/mensaje'
      path: '/nuevo/mensaje'
      fullPath: '/nuevo/mensaje'
      preLoaderRoute: typeof NuevoMensajeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nuevo/pago': {
      id: '/nuevo/pago'
      path: '/nuevo/pago'
      fullPath: '/nuevo/pago'
      preLoaderRoute: typeof NuevoPagoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NuevoCarritoRoute: NuevoCarritoRoute,
  NuevoCategoriaRoute: NuevoCategoriaRoute,
  NuevoConfirmacionRoute: NuevoConfirmacionRoute,
  NuevoConfirmarRoute: NuevoConfirmarRoute,
  NuevoMensajeRoute: NuevoMensajeRoute,
  NuevoPagoRoute: NuevoPagoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
